package org.example.rowingcoaching.mapper;

import org.example.rowingcoaching.dto.TeamDTO;
import org.example.rowingcoaching.model.Team;
import org.example.rowingcoaching.dto.request.CreateTeamRequest;

public class TeamMapper {

    public static TeamDTO toDTO(Team team) {
        return new TeamDTO(
                team.getId(),
                team.getTeamName(),
                team.getTeamCode(),
                team.getLogo()
        );
    }

    public static Team fromCreateRequest(CreateTeamRequest request) {
        Team team = new Team();
        team.setTeamName(request.getName());
        team.setLogo(request.getLogo());
        // teamCode will be generated by TeamService.createTeam method
        return team;
    }
}

